#########################
# Featured publications #
#########################

- id: doi:10.1038/s41592-023-02139-9
  _title: A fast, scalable and versatile tool for analysis of single-cell omics data
  image: https://media.springernature.com/w440/springer-static/cover-hires/journal/41592/20/12
  group: featured
  buttons:
    - type: website
      link: https://kzhang.org/SnapATAC2/
    - type: source
      text: Code
      link: https://github.com/kaizhang/SnapATAC2

- id: doi:10.1016/j.cell.2021.10.024
  _title: A single-cell atlas of chromatin accessibility in the human genome
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867420X00250-cov200h.gif
  group: featured
  buttons:
    - type: website
      link: http://catlas.org/catlas_humanenhancer
    - type: source
      text: Code
      link: https://gitlab.com/kaizhang/hea2
    - type: data
      text: Data
      link: https://data.mendeley.com/datasets/yv4fzv6cnm

- id: doi:10.1126/sciadv.aav3262
  _title: "Taiji: System-level identification of key transcription factors reveals transcriptional waves in mouse embryonic development"
  image: https://www.science.org/cms/asset/7757979b-746e-490b-b3a4-c75f5f7c27d5/sciadv.2019.5.issue-3.largecover.jpg
  group: featured

- id: doi:10.1038/ncomms12249
  _title: Systematic identification of protein combinations mediating chromatin looping
  image: https://upload.wikimedia.org/wikipedia/en/b/bf/Nature_Communications_-_Journal_Cover.jpg
  group: featured

- id: doi:10.1038/ni.3706
  _title: Epigenetic landscapes reveal transcription factors that regulate CD8+ T cell differentiation
  image: https://media.springernature.com/w200/springer-static/cover-hires/journal/41590/18/3
  group: featured

###########################
# Other publications ######
###########################

- id: doi:10.1073/pnas.2410092122
  _title: Genomic analysis of progenitors in viral infection implicates glucocorticoids as suppressors of plasmacytoid dendritic cell generation
- id: doi:10.1038/s41586-025-08603-0
  _title: Sensory input, sex and function shape hypothalamic cell type development
- id: doi:10.1038/s41586-023-06824-9
  _title: Single-cell analysis of chromatin accessibility in the adult mouse brain
- id: doi:10.1016/j.celrep.2022.111630
  _title: Systematic discovery and functional dissection of enhancers needed for cancer cell fitness and proliferation
  image: https://www.cell.com/cms/attachment/dd685e42-1bfd-4c62-a488-48cc64b0bc04/fx1.jpg
- id: doi:10.1038/s41467-022-33785-w
- id: doi:10.1038/s41586-021-03604-1
- id: doi:10.7554/elife.62522
- id: doi:10.1126/sciadv.abf1444
- id: doi:10.1038/s41467-021-21583-9
- id: doi:10.1534/genetics.120.303597
- id: doi:10.1093/nar/gkz483
- id: doi:10.1038/nature24993
- id: doi:10.1073/pnas.1813565116
- id: doi:10.1093/nar/gkr698
- id: doi:10.1093/database/bay017
- id: doi:10.1534/g3.118.200401
- id: doi:10.1038/ncomms10812
- id: doi:10.1038/s41525-019-0077-8
- id: doi:10.1016/j.ymeth.2010.04.005
- id: doi:10.1073/pnas.2210991120
  _title: Integrated analysis of single-cell chromatin state and transcriptome identified common vulnerability despite glioblastoma heterogeneity